name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js (if applicable)
      uses: actions/setup-node@v2
      with:
        node-version: '14'  # Adjust the version based on your project

    - name: Install dependencies
      run: |
        npm install  # or 'yarn install', depending on your project

    - name: Build project
      run: |
        npm run build  # or any other build command for your project

    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: my-artifact
        path: ./build/*  # Ensure this path is where your built files are located

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Download artifact
      uses: actions/download-artifact@v3
      with:
        name: my-artifact
        path: ./downloaded

    - name: Set up Git
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"

    - name: Deploy to GitHub Pages
      run: |
        # Move the files from 'downloaded' to the root (or gh-pages branch folder)
        mv ./downloaded/* ./

        # Initialize a new Git repo and switch to the gh-pages branch
        git init
        git checkout -b gh-pages

        # Add all the files and commit
        git add .
        git commit -m "Deploy to GitHub Pages"

        # Push the changes to the gh-pages branch
        git push --force https://github.com/${{ github.repository }} gh-pages:gh-pages
