name: Deploy to GitHub Pages
on:
  push:
    branches:
      - main  # Change to your main branch name

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Pages
        uses: actions/configure-pages@v3

      - name: Upload Pages Artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: .  # Change this if your files are inside a subfolder

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v1

